import useSWR from "swr"; import {fetcher,RunReport,Attestation} from "../lib/api";
function Score({value,label}:{value:number;label:string}){const pct=Math.round(value*100);return <div><div className="mb-1 flex justify-between text-xs"><span className="text-zinc-500">{label}</span><span className="font-mono text-zinc-300">{pct}%</span></div><div className="h-2 overflow-hidden rounded bg-zinc-800"><div className={`h-full ${pct>=90?"bg-emerald-600":pct>=70?"bg-amber-600":"bg-rose-600"}`} style={{width:`${Math.max(0,Math.min(100,pct))}%`}}/></div></div>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-lg border border-zinc-800 bg-[#0f141b] p-5"><h2 className="mb-3 text-sm font-medium text-zinc-300">{title}</h2>{children}</section>}
function Chain({items}:{items:string[]}){return <div className="flex flex-wrap items-center gap-1.5">{items.map((x,i)=><div key={x+i} className="flex items-center gap-1.5"><span className="rounded border border-zinc-700 bg-zinc-900 px-2 py-1 font-mono text-xs text-zinc-300">{x}</span>{i<items.length-1&&<span className="text-zinc-700">→</span>}</div>)}</div>}
export default function ReportViewer({runId}:{runId:string}){const{data:report,error}=useSWR<RunReport>(`/runs/${runId}/report`,fetcher,{refreshInterval:5000});const{data:attestation}=useSWR<Attestation>(report?.passed?`/runs/${runId}/attestation`:null,fetcher);if(error)return <Section title="Pipeline report"><p className="text-sm text-zinc-600">No report yet — the worker may still be running.</p></Section>;if(!report)return <Section title="Pipeline report"><p className="text-sm text-zinc-600">Loading pipeline evidence…</p></Section>;const st=report.stages;return <div className="space-y-4">
 {st.translate&&<Section title="Sigma translation"><div className="grid gap-3 md:grid-cols-2"><div><p className="text-xs text-zinc-600">Status</p><p className="mt-1 text-sm text-zinc-300">{st.translate.status||"available"}</p></div><div><p className="text-xs text-zinc-600">Query artifact</p><p className="mt-1 truncate font-mono text-xs text-zinc-400">{st.translate.query_dsl_path||"not recorded"}</p></div></div></Section>}
 {st.baseline&&<Section title="Benign baseline"><div className="grid gap-4 md:grid-cols-3"><div><p className="text-xs text-zinc-600">Events indexed</p><p className="mt-1 text-lg text-zinc-200">{st.baseline.events_indexed?.toLocaleString()||"—"}</p></div><div><p className="text-xs text-zinc-600">Status</p><p className="mt-1 text-sm text-zinc-300">{st.baseline.status||"—"}</p></div><div><p className="text-xs text-zinc-600">Purpose</p><p className="mt-1 text-xs text-zinc-500">Measure benign-noise behavior before promotion.</p></div></div></Section>}
 {st.attack_simulation?.simulated_chain&&<Section title="Simulated attack chain · MITRE ATT&CK"><Chain items={st.attack_simulation.simulated_chain}/><p className="mt-3 text-xs text-zinc-600">{st.attack_simulation.simulated_user} on {st.attack_simulation.simulated_host} · {st.attack_simulation.events_indexed} events indexed</p>{st.attack_simulation.rule_tagged_techniques&&<p className="mt-2 text-xs text-zinc-600">Rule-tagged techniques: {st.attack_simulation.rule_tagged_techniques.join(", ")||"none"}</p>}</Section>}
 {st.validate&&<Section title="Detection validation"><div className="grid gap-4 md:grid-cols-2"><div><p className="text-xs text-zinc-500">Fired on attack telemetry</p><p className={st.validate.fired_on_attack?"text-emerald-400":"text-rose-400"}>{st.validate.fired_on_attack?`Yes (${st.validate.attack_hit_count} hits)`:"No"}</p></div><div><p className="text-xs text-zinc-500">Fired on baseline noise</p><p className={st.validate.fired_on_baseline?"text-rose-400":"text-emerald-400"}>{st.validate.fired_on_baseline?`Yes (${st.validate.baseline_hit_count} hits)`:"No"}</p></div></div>{st.validate.false_positive_rate!==undefined&&<div className="mt-4"><Score value={1-st.validate.false_positive_rate} label="Baseline precision"/></div>}</Section>}
 {st.robustness&&<Section title="Adversarial evasion robustness">{st.robustness.score!==undefined&&<Score value={st.robustness.score} label="Mutation variants still detected"/>}<p className="mt-2 text-xs text-zinc-600">{st.robustness.variants_detected??0} / {st.robustness.variants_tested??0} variants detected.</p>{st.robustness.undetected_examples?.length? <div className="mt-4 space-y-2">{st.robustness.undetected_examples.map((e,i)=><div key={i} className="rounded bg-zinc-900 p-2 text-xs text-zinc-500"><span className="text-amber-500">[{e.mutation_chain.join(", ")}]</span> {String(e.event.command_line||JSON.stringify(e.event))}</div>)}</div>:<p className="mt-3 text-xs text-zinc-600">No undetected examples recorded.</p>}</Section>}
 {st.quality_score&&<Section title="Detection quality score"><div className="grid gap-4 md:grid-cols-3"><div><p className="text-xs text-zinc-600">Score</p><p className="mt-1 text-2xl text-zinc-100">{st.quality_score.score??"—"} <span className="text-xs text-zinc-600">/ {st.quality_score.max??100}</span></p></div><div><p className="text-xs text-zinc-600">Rating</p><p className="mt-1 text-sm text-zinc-300">{st.quality_score.rating||"—"}</p></div><div><p className="text-xs text-zinc-600">Components</p><div className="mt-1 space-y-1">{Object.entries(st.quality_score.components||{}).map(([k,v])=><div key={k} className="flex justify-between text-xs"><span className="text-zinc-600">{k}</span><span className="text-zinc-400">{v}</span></div>)}</div></div></div></Section>}
 {st.soar_playbook&&<Section title="SOAR playbook"><p className={st.soar_playbook.status==="ok"?"text-sm text-emerald-400":"text-sm text-rose-400"}>{st.soar_playbook.status||"unknown"}</p>{st.soar_playbook.path&&<p className="mt-2 font-mono text-xs text-zinc-400">{st.soar_playbook.path}</p>}{st.soar_playbook.pr_url&&<a href={st.soar_playbook.pr_url} target="_blank" rel="noreferrer" className="mt-2 inline-block text-xs text-sky-400 hover:underline">Review generated PR →</a>}{st.soar_playbook.error&&<p className="mt-2 text-xs text-rose-400">{st.soar_playbook.error}</p>}</Section>}
 {attestation&&<Section title="Signed provenance attestation"><div className="grid gap-y-2 text-xs md:grid-cols-[160px_1fr]"><span className="text-zinc-500">Issuer</span><span className="text-zinc-300">{attestation.attestation.issuer}</span><span className="text-zinc-500">Issued at</span><span className="text-zinc-300">{new Date(attestation.attestation.issued_at).toLocaleString()}</span><span className="text-zinc-500">Rule SHA-256</span><span className="truncate font-mono text-zinc-400">{attestation.attestation.rule_content_sha256}</span><span className="text-zinc-500">Signature</span><span className="truncate font-mono text-zinc-400">{attestation.signature}</span></div></Section>}
 </div>}
