import Link from "next/link";
import useSWR from "swr";
import { fetcher, RunStatus } from "../lib/api";
import PlatformNav from "../components/PlatformNav";
import ThemeToggle from "../components/ThemeToggle";
import ApiKeyBar from "../components/ApiKeyBar";

export default function Automation() {
  const { data: runs } = useSWR<RunStatus[]>("/runs", fetcher, { refreshInterval: 5000 });
  const soar = runs?.filter(r => r.stage === "soar" || r.stage === "done").length ?? 0;
  return <main className="min-h-screen bg-[#0a0e13] text-zinc-200"><header className="border-b border-zinc-800 bg-[#0d1117]/95 px-6 py-5 lg:px-10"><div className="mx-auto flex max-w-7xl items-center justify-between"><div><Link href="/" className="text-xl font-semibold tracking-[0.18em]">WRAITH</Link><p className="mt-1 text-xs text-zinc-600">Automation</p></div><div className="flex gap-2"><ThemeToggle /><ApiKeyBar /></div></div></header><div className="mx-auto grid max-w-7xl gap-6 px-6 py-6 lg:grid-cols-[210px_1fr] lg:px-10"><aside className="hidden lg:block"><PlatformNav /></aside><section><div className="rounded-xl border border-zinc-800 bg-[#0f141b] p-6"><p className="text-[10px] uppercase tracking-[0.2em] text-emerald-400">Operational automation</p><h1 className="mt-2 text-3xl font-semibold">Automation</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-zinc-500">Automation connects validated detection changes to CI/CD, SOAR and repository workflows. The UI distinguishes local pipeline behavior from external provider-dependent actions.</p></div><div className="mt-6 grid gap-3 md:grid-cols-3"><div className="rounded-lg border border-zinc-800 bg-[#0f141b] p-5"><p className="text-xs font-semibold">CI / CD</p><p className="mt-2 text-xs leading-5 text-zinc-600">Detection changes can enter the Wraith lifecycle through repository and CI automation.</p><p id="cicd" className="mt-4 text-[10px] uppercase tracking-wider text-emerald-400">Repository boundary</p></div><div className="rounded-lg border border-zinc-800 bg-[#0f141b] p-5"><p className="text-xs font-semibold">SOAR</p><p className="mt-2 text-xs leading-5 text-zinc-600">Completed validation runs can carry SOAR playbook evidence in their reports.</p><p className="mt-4 text-[10px] uppercase tracking-wider text-zinc-500">{soar} relevant runs observed</p></div><div className="rounded-lg border border-zinc-800 bg-[#0f141b] p-5"><p className="text-xs font-semibold">Webhooks</p><p className="mt-2 text-xs leading-5 text-zinc-600">Webhook events provide the trigger boundary for automated validation workflows.</p><p className="mt-4 text-[10px] uppercase tracking-wider text-zinc-500">Control-plane integration</p></div></div><div className="mt-6 rounded-lg border border-zinc-800 bg-[#0f141b] p-5"><h2 className="text-sm font-semibold">Automation principle</h2><p className="mt-3 max-w-3xl text-xs leading-6 text-zinc-600">Wraith should automate evidence collection and workflow transitions, not silently bypass human governance. Approval and provenance remain explicit gates before deployment.</p></div></section></div></main>;
}
