import useSWR from "swr";
import Link from "next/link";
import {useMemo,useState} from "react";
import {fetcher,RunStatus,HealthStatus,Session} from "../lib/api";
import ApiKeyBar from "../components/ApiKeyBar";
import PlatformNav from "../components/PlatformNav";
import ThemeToggle from "../components/ThemeToggle";

const STAGE_LABEL:Record<string,string>={lint:"Linting",provision:"Provisioning",simulate:"Simulation",validate:"Validation",soar:"SOAR",done:"Complete",failed:"Failed"};
function StatusBadge({run}:{run:RunStatus}){const failed=run.stage==="failed"||run.passed===false;const terminal=run.stage==="done"||run.stage==="failed";const tone=terminal?(failed?"border-rose-900 bg-rose-950/60 text-rose-300":"border-emerald-900 bg-emerald-950/60 text-emerald-300"):"border-amber-900 bg-amber-950/60 text-amber-300";return <span className={`rounded border px-2 py-1 text-[11px] font-medium ${tone}`}>{STAGE_LABEL[run.stage]||run.stage}</span>}
function Metric({label,value,detail}:{label:string;value:string|number;detail:string}){return <div className="rounded-lg border border-zinc-800 bg-[#11161d] p-4"><p className="text-[10px] uppercase tracking-[.16em] text-zinc-600">{label}</p><p className="mt-2 text-2xl font-semibold text-zinc-100">{value}</p><p className="mt-1 text-xs text-zinc-600">{detail}</p></div>}
function Health({name,data}:{name:string;data?:HealthStatus}){const ok=!!data&&(data.status==="ok"||data.ready===true);return <div className="rounded border border-zinc-800 bg-[#0a0e13] p-4"><div className="flex items-center justify-between"><span className="text-xs text-zinc-400">{name}</span><span className={`h-2 w-2 rounded-full ${ok?"bg-emerald-400":"bg-amber-400"}`}/></div><p className="mt-2 text-[10px] text-zinc-700">{data?ok?"healthy":data.error||"degraded":"checking…"}</p></div>}
export default function Home(){
 const{data:runs,error,isLoading}=useSWR<RunStatus[]>("/runs",fetcher,{refreshInterval:4000});
 const{data:health}=useSWR<HealthStatus>("/healthz",fetcher,{refreshInterval:10000});
 const{data:ready}=useSWR<HealthStatus>("/readyz",fetcher,{refreshInterval:10000});
 const{data:session}=useSWR<Session>("/session",fetcher);
 const[q,setQ]=useState("");const[status,setStatus]=useState("all");
 const filtered=useMemo(()=>{if(!runs)return[];const x=q.trim().toLowerCase();return runs.filter(r=>{const match=!x||[r.run_id,r.rule_path,r.rule_title,r.repo,r.rule_id].some(v=>v?.toLowerCase().includes(x));const st=status==="all"||(status==="passed"&&r.stage==="done"&&r.passed===true)||(status==="failed"&&(r.stage==="failed"||r.passed===false))||(status==="active"&&r.stage!=="done"&&r.stage!=="failed");return match&&st})},[runs,q,status]);
 const total=runs?.length||0,passed=runs?.filter(r=>r.stage==="done"&&r.passed===true).length||0,failed=runs?.filter(r=>r.stage==="failed"||r.passed===false).length||0,active=total-passed-failed;
 return <main className="min-h-screen bg-[#0a0e13] text-zinc-200"><header className="border-b border-zinc-800 bg-[#0d1117]/95 px-6 py-5 lg:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-3"><span className="h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_12px_rgba(52,211,153,.55)]"/><h1 className="text-xl font-semibold tracking-[.18em] text-zinc-100">WRAITH</h1><span className="rounded border border-zinc-800 px-2 py-0.5 text-[10px] uppercase tracking-widest text-zinc-600">Detection Engineering & Validation</span></div><p className="mt-2 max-w-3xl text-sm text-zinc-500">A control plane for developing, breaking, validating, attesting and promoting security detections.</p></div><div className="flex flex-wrap items-center justify-end gap-2"><Link href="/rules" className="rounded-md border border-zinc-800 px-3 py-2 text-xs text-zinc-400 hover:bg-zinc-900">Rules</Link><Link href="/audit" className="rounded-md border border-zinc-800 px-3 py-2 text-xs text-zinc-400 hover:bg-zinc-900">Audit</Link><Link href="/playground" className="rounded-md border border-zinc-700 px-3 py-2 text-xs text-zinc-300 hover:bg-zinc-900">Playground</Link><ThemeToggle/><ApiKeyBar/></div></div></div></header>
 <div className="mx-auto grid max-w-7xl gap-6 px-6 py-6 lg:grid-cols-[210px_1fr] lg:px-10"><aside className="hidden lg:block"><PlatformNav/></aside><section className="min-w-0">
 <section className="rounded-xl border border-zinc-800 bg-[#0f141b] p-6 md:p-8"><div className="flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] uppercase tracking-[.2em] text-emerald-400">Wraith control plane</p><h2 className="mt-3 max-w-4xl text-3xl font-semibold tracking-tight text-zinc-100 md:text-4xl">Build detections. Break them. Measure them. Validate them.</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-zinc-500">The UI now maps directly to backend capabilities: rules and linting, durable runs, live events, validation evidence, ATT&CK chains, robustness, quality, SOAR, provenance, approval, deployment and audit.</p></div>{session&&<div className="shrink-0 rounded border border-zinc-800 bg-[#0a0e13] p-3"><p className="text-[9px] uppercase tracking-wider text-zinc-700">Authenticated</p><p className="mt-1 text-xs text-zinc-300">{session.label}</p><p className="mt-1 text-[10px] text-emerald-400">{session.role}</p></div>}</div></section>
 <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Validation runs" value={total} detail="Persisted pipeline executions"/><Metric label="Passed" value={passed} detail="Completed successfully"/><Metric label="Failed" value={failed} detail="Failed or rejected"/><Metric label="Active" value={active} detail="Currently processing"/></section>
 <section id="runs" className="mt-6 rounded-lg border border-zinc-800 bg-[#0f141b]"><div className="flex flex-col gap-3 border-b border-zinc-800 p-4 md:flex-row md:items-center md:justify-between"><div><h2 className="text-sm font-semibold text-zinc-200">Validation runs</h2><p className="mt-1 text-xs text-zinc-600">Live pipeline state and real persisted run records.</p></div><div className="flex flex-col gap-2 sm:flex-row"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search runs, rules, repositories…" className="w-full rounded-md border border-zinc-800 bg-[#0a0e13] px-3 py-2 text-xs text-zinc-300 outline-none placeholder:text-zinc-700 focus:border-zinc-600 sm:w-64"/><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-md border border-zinc-800 bg-[#0a0e13] px-3 py-2 text-xs text-zinc-400 outline-none"><option value="all">All status</option><option value="active">Active</option><option value="passed">Passed</option><option value="failed">Failed</option></select></div></div>{isLoading&&<p className="p-8 text-sm text-zinc-600">Loading validation runs…</p>}{error&&<p className="m-4 rounded-md border border-rose-900/80 bg-rose-950/30 p-4 text-sm text-rose-300">{error.message}</p>}{runs&&filtered.length===0&&<p className="p-10 text-center text-sm text-zinc-600">No runs match the current filters.</p>}<div className="divide-y divide-zinc-800/80">{filtered.map(run=><Link key={run.run_id} href={`/runs/${run.run_id}`} className="block px-4 py-4 transition hover:bg-zinc-900/40"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div className="min-w-0"><div className="flex items-center gap-2"><span className="truncate font-mono text-sm text-zinc-200">{run.rule_title||run.rule_path}</span><StatusBadge run={run}/></div><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-[11px] text-zinc-600"><span className="font-mono">{run.run_id}</span><span>{run.repo} · PR #{run.pr_number}</span><span>{new Date(run.updated_at).toLocaleString()}</span></div></div><span className="text-xs text-zinc-700">Open evidence →</span></div></Link>)}</div></section>
 <section id="evidence" className="mt-8"><div><p className="text-[10px] uppercase tracking-[.18em] text-zinc-700">Backend evidence</p><h2 className="mt-1 text-sm font-semibold text-zinc-200">Every major pipeline capability has a UI destination</h2><p className="mt-1 text-xs leading-5 text-zinc-600">Run detail is the evidence hub; the rules and audit workspaces expose control-plane resources directly.</p></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{[["Sigma translation","Compiled query and translation status are shown in run reports."],["MITRE ATT&CK","Simulated techniques and attack chains are rendered from report evidence."],["Detection validation","Attack hits, baseline hits, scan counts and false-positive rate are displayed."],["Mutation / robustness","Variant coverage and undetected examples are rendered from the robustness stage."],["Quality scoring","Quality components and scores are displayed when produced by the engine."],["SOAR + provenance","Playbook output and signed attestation metadata are visible before promotion."]].map(([t,d])=><div key={t} className="rounded-lg border border-zinc-800 bg-[#0f141b] p-5"><h3 className="text-xs font-semibold text-zinc-200">{t}</h3><p className="mt-2 text-xs leading-5 text-zinc-600">{d}</p></div>)}</div></section>
 <section id="system" className="mt-8 rounded-lg border border-zinc-800 bg-[#0f141b] p-5"><div className="flex flex-col gap-2 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] uppercase tracking-[.18em] text-zinc-700">Runtime</p><h2 className="mt-1 text-sm font-semibold text-zinc-200">Control-plane health</h2><p className="mt-1 text-xs text-zinc-600">Liveness and readiness are real backend probes. The validation dependencies are represented by the pipeline's provisioned environment and report stages.</p></div><span className="text-[10px] text-zinc-700">polling automatically</span></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><Health name="Go API / liveness" data={health}/><Health name="Store / readiness" data={ready}/></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Link href="/rules" className="rounded border border-zinc-800 bg-[#0a0e13] p-4 hover:border-zinc-700"><p className="text-xs text-zinc-300">Rules workspace</p><p className="mt-1 text-[10px] text-zinc-700">Browse source + lint evidence</p></Link><Link href="/audit" className="rounded border border-zinc-800 bg-[#0a0e13] p-4 hover:border-zinc-700"><p className="text-xs text-zinc-300">Audit trail</p><p className="mt-1 text-[10px] text-zinc-700">Governance events</p></Link><Link href="/introduction" className="rounded border border-zinc-800 bg-[#0a0e13] p-4 hover:border-zinc-700"><p className="text-xs text-zinc-300">Architecture</p><p className="mt-1 text-[10px] text-zinc-700">Control-plane model</p></Link></div></section>
 <footer className="py-10 text-xs text-zinc-700">WRAITH · Detection engineering, validation, provenance and controlled deployment</footer>
 </section></div></main>
}
