import {useEffect,useState} from "react";
import Link from "next/link";
import PlatformNav from "../components/PlatformNav";
import {fetchHealth,fetchReady} from "../lib/api";

type Probe={status?:string;ready?:boolean;error?:string};
type Service={name:string;role:string;surface:string;state:"healthy"|"dependency"|"external";detail:string};
export default function Integrations(){
 const [health,setHealth]=useState<Probe|null>(null);const [ready,setReady]=useState<Probe|null>(null);const [error,setError]=useState("");
 const load=async()=>{try{const [h,r]=await Promise.all([fetchHealth(),fetchReady()]);setHealth(h);setReady(r)}catch(e){setError(e instanceof Error?e.message:"Unable to reach API")}};
 useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);
 const services:Service[]=[
  {name:"Go control plane",role:"HTTP API, RBAC, approval and deployment gates",surface:"/healthz",state:"healthy",detail:health?.status==="ok"?"Liveness probe passing":"Waiting for liveness"},
  {name:"PostgreSQL",role:"Durable runs, queue state and audit trail",surface:"/readyz",state:ready?.ready?"healthy":"dependency",detail:ready?.ready?"Store readiness confirmed":"Store readiness unavailable"},
  {name:"Elasticsearch / OpenSearch",role:"Detection validation and production rule adapter",surface:"SIEM",state:"dependency",detail:"Used by the validation and deployment paths; provider state is surfaced through pipeline evidence."},
  {name:"Neo4j",role:"MITRE ATT&CK attack graph and campaign relationships",surface:"Attack graph",state:"dependency",detail:"Used by the attack simulation stage; results are attached to run evidence."},
  {name:"GitHub",role:"Pull-request webhook trigger and CI integration",surface:"/webhook/github",state:"external",detail:"Webhook receiver is HMAC-verified before rules are queued."},
  {name:"Slack-compatible notifications",role:"Completion and human approval notifications",surface:"Notifier",state:"external",detail:"Optional webhook integration; delivery failures do not replace the approval gate."},
  {name:"Prometheus",role:"Runtime and detection-engineering telemetry",surface:"/metrics",state:"healthy",detail:"Metrics endpoint is unauthenticated for scraper compatibility."},
 ];
 return <div className="min-h-screen bg-[#070707] text-zinc-200"><div className="mx-auto grid max-w-[1500px] grid-cols-[220px_1fr] gap-10 px-8 py-8"><PlatformNav/><main>
 <div className="mb-8 flex items-start justify-between"><div><div className="text-[10px] uppercase tracking-[0.22em] text-zinc-600">System / Integration boundaries</div><h1 className="mt-2 text-3xl font-semibold tracking-tight">Integrations & runtime</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-zinc-500">One control-plane view of Wraith's persistence, detection infrastructure, graph engine, CI trigger and notification boundaries. Provider claims are kept separate from live validation evidence.</p></div><Link href="/metrics" className="rounded-md border border-zinc-800 px-3 py-2 text-xs text-zinc-400 hover:border-zinc-600 hover:text-zinc-200">Open telemetry</Link></div>
 {error&&<div className="mb-5 rounded-md border border-red-950 bg-red-950/20 px-4 py-3 text-xs text-red-300">{error}</div>}
 <div className="mb-6 grid gap-3 md:grid-cols-3"><div className="rounded-xl border border-zinc-900 bg-zinc-950 p-4"><div className="text-[10px] uppercase tracking-widest text-zinc-600">Liveness</div><div className="mt-2 text-lg font-semibold">{health?.status==="ok"?"Operational":"Checking…"}</div></div><div className="rounded-xl border border-zinc-900 bg-zinc-950 p-4"><div className="text-[10px] uppercase tracking-widest text-zinc-600">Readiness</div><div className="mt-2 text-lg font-semibold">{ready?.ready?"Ready":"Degraded / checking"}</div></div><div className="rounded-xl border border-zinc-900 bg-zinc-950 p-4"><div className="text-[10px] uppercase tracking-widest text-zinc-600">Evidence model</div><div className="mt-2 text-lg font-semibold">Run-scoped</div></div></div>
 <div className="overflow-hidden rounded-xl border border-zinc-900 bg-zinc-950"><div className="grid grid-cols-[1fr_1.2fr_130px] gap-4 border-b border-zinc-900 px-5 py-3 text-[10px] uppercase tracking-widest text-zinc-600"><span>Boundary</span><span>Responsibility</span><span>State</span></div>{services.map(s=><div key={s.name} className="grid grid-cols-[1fr_1.2fr_130px] gap-4 border-b border-zinc-900 px-5 py-4"><div><div className="text-sm font-medium">{s.name}</div><div className="mt-1 font-mono text-[10px] text-zinc-700">{s.surface}</div></div><div><div className="text-xs text-zinc-400">{s.role}</div><div className="mt-1 text-[11px] leading-5 text-zinc-600">{s.detail}</div></div><div><span className={`inline-flex rounded-full border px-2 py-0.5 text-[10px] uppercase tracking-wider ${s.state==="healthy"?"border-emerald-900 bg-emerald-950/30 text-emerald-300":s.state==="dependency"?"border-amber-900 bg-amber-950/30 text-amber-300":"border-zinc-800 bg-zinc-900 text-zinc-400"}`}>{s.state}</span></div></div>)}</div>
 <div className="mt-6 grid gap-4 md:grid-cols-2"><Link href="/#evidence" className="rounded-xl border border-zinc-900 bg-zinc-950 p-5 hover:border-zinc-700"><div className="text-xs font-semibold">Detection evidence</div><p className="mt-2 text-xs leading-5 text-zinc-600">Open a validation run to inspect Sigma translation, attack simulation, baseline noise, mutation results and quality scoring.</p></Link><Link href="/audit" className="rounded-xl border border-zinc-900 bg-zinc-950 p-5 hover:border-zinc-700"><div className="text-xs font-semibold">Governance</div><p className="mt-2 text-xs leading-5 text-zinc-600">Review authenticated actions, approvals, deployment events and operational mutations in the audit trail.</p></Link></div>
 </main></div></div>