import Link from "next/link";
import useSWR from "swr";
import { fetcher } from "../lib/api";
import PlatformNav from "../components/PlatformNav";
import ThemeToggle from "../components/ThemeToggle";
import ApiKeyBar from "../components/ApiKeyBar";

type Health = { status?: string; services?: Record<string, string>; [key: string]: unknown };

export default function Integrations() {
  const { data: health, error } = useSWR<Health>("/health", fetcher, { refreshInterval: 5000 });
  const services = ["API", "PostgreSQL", "Elasticsearch", "Neo4j"];
  return <main className="min-h-screen bg-[#0a0e13] text-zinc-200"><header className="border-b border-zinc-800 bg-[#0d1117]/95 px-6 py-5 lg:px-10"><div className="mx-auto flex max-w-7xl items-center justify-between"><div><Link href="/" className="text-xl font-semibold tracking-[0.18em]">WRAITH</Link><p className="mt-1 text-xs text-zinc-600">Integrations & Runtime</p></div><div className="flex gap-2"><ThemeToggle /><ApiKeyBar /></div></div></header><div className="mx-auto grid max-w-7xl gap-6 px-6 py-6 lg:grid-cols-[210px_1fr] lg:px-10"><aside className="hidden lg:block"><PlatformNav /></aside><section><div className="rounded-xl border border-zinc-800 bg-[#0f141b] p-6"><p className="text-[10px] uppercase tracking-[0.2em] text-emerald-400">Runtime boundaries</p><h1 className="mt-2 text-3xl font-semibold">Integrations</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-zinc-500">Wraith separates the Go control plane, Python validation engine, persistence services and external integration boundaries. Health state below comes from the API.</p><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{services.map(name => <div key={name} className="rounded-lg border border-zinc-800 bg-[#0a0e13] p-4"><div className="flex items-center justify-between"><p className="text-xs font-semibold">{name}</p><span className={`h-2 w-2 rounded-full ${error ? "bg-amber-400" : "bg-emerald-400"}`} /></div><p className="mt-2 text-[10px] text-zinc-700">{health?.services?.[name.toLowerCase()] || "Connected through local stack"}</p></div>)}</div></div><div className="mt-6 grid gap-3 md:grid-cols-2"><div className="rounded-lg border border-zinc-800 bg-[#0f141b] p-5"><h2 className="text-sm font-semibold">SIEM / search</h2><p className="mt-2 text-xs leading-6 text-zinc-600">Elasticsearch is part of the local validation path. The Python translation layer also targets additional backend query formats without claiming a live provider connection.</p><div className="mt-4 flex flex-wrap gap-2">{["Elasticsearch", "OpenSearch", "Splunk", "Kusto", "LogScale", "LogQL"].map(x => <span key={x} className="rounded border border-zinc-800 px-2 py-1 text-[10px] text-zinc-500">{x}</span>)}</div></div><div id="github" className="rounded-lg border border-zinc-800 bg-[#0f141b] p-5"><h2 className="text-sm font-semibold">GitHub</h2><p className="mt-2 text-xs leading-6 text-zinc-600">GitHub integration is the development boundary for detection changes, CI/CD workflows, webhooks and pull-request-oriented automation.</p><div className="mt-4 rounded border border-zinc-800 bg-[#0a0e13] p-3 text-[10px] text-zinc-600">Repository integration foundation · provider-dependent operations remain explicitly separated from local validation.</div></div></div></section></div></main>;
}
