import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import PlatformNav from "../components/PlatformNav";
import {PipelineJob,fetchJobs,retryJob} from "../lib/api";

function badge(status:string){const cls=status==="succeeded"?"text-emerald-300 bg-emerald-950/40 border-emerald-900":status==="failed"?"text-red-300 bg-red-950/40 border-red-900":status==="running"?"text-sky-300 bg-sky-950/40 border-sky-900":status==="cancelled"?"text-amber-300 bg-amber-950/40 border-amber-900":"text-zinc-300 bg-zinc-900 border-zinc-800";return <span className={`inline-flex rounded-full border px-2 py-0.5 text-[10px] uppercase tracking-wider ${cls}`}>{status}</span>}

export default function JobsPage(){
 const [jobs,setJobs]=useState<PipelineJob[]>([]); const [q,setQ]=useState(""); const [status,setStatus]=useState("all"); const [error,setError]=useState(""); const [busy,setBusy]=useState<number|null>(null);
 const load=()=>fetchJobs().then(setJobs).catch(e=>setError(e.message));
 useEffect(()=>{load();const t=setInterval(load,3000);return()=>clearInterval(t)},[]);
 const filtered=useMemo(()=>jobs.filter(j=>(status==="all"||j.status===status)&&(!q||[j.run_id,j.rule_path,j.last_error||""].join(" ").toLowerCase().includes(q.toLowerCase()))),[jobs,q,status]);
 const counts=useMemo(()=>jobs.reduce((a,j)=>(a[j.status]=(a[j.status]||0)+1,a),{} as Record<string,number>),[jobs]);
 async function retry(id:number){setBusy(id);setError("");try{const r=await retryJob(id);if(!r.ok)throw new Error(r.data?.error||"Retry failed");await load()}catch(e){setError(e instanceof Error?e.message:"Retry failed")}finally{setBusy(null)}}
 return <div className="min-h-screen bg-[#070707] text-zinc-200"><div className="mx-auto grid max-w-[1500px] grid-cols-[220px_1fr] gap-10 px-8 py-8"><PlatformNav/><main>
 <div className="mb-8 flex items-start justify-between gap-6"><div><div className="text-[10px] uppercase tracking-[0.22em] text-zinc-600">Operations / Durable execution</div><h1 className="mt-2 text-3xl font-semibold tracking-tight">Pipeline jobs</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-500">Inspect queued, running, retried, failed, and cancelled pipeline work. This is the operational view over the durable worker queue.</p></div><button onClick={load} className="rounded-md border border-zinc-800 px-3 py-2 text-xs text-zinc-400 hover:border-zinc-600 hover:text-zinc-200">Refresh</button></div>
 <div className="grid grid-cols-5 gap-3 mb-6">{["queued","running","succeeded","failed","cancelled"].map(s=><button key={s} onClick={()=>setStatus(s)} className={`rounded-lg border p-4 text-left ${status===s?"border-zinc-500 bg-zinc-900":"border-zinc-900 bg-zinc-950"}`}><div className="text-[10px] uppercase tracking-widest text-zinc-600">{s}</div><div className="mt-2 text-2xl font-semibold">{counts[s]||0}</div></button>)}</div>
 <div className="mb-4 flex gap-3"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search run ID, rule path, error..." className="w-full rounded-md border border-zinc-900 bg-zinc-950 px-3 py-2 text-sm outline-none placeholder:text-zinc-700 focus:border-zinc-700"/><button onClick={()=>setStatus("all")} className="rounded-md border border-zinc-800 px-3 text-xs text-zinc-400">All</button></div>
 {error&&<div className="mb-4 rounded-md border border-red-950 bg-red-950/20 px-4 py-3 text-xs text-red-300">{error}</div>}
 <div className="overflow-hidden rounded-xl border border-zinc-900 bg-zinc-950"><div className="grid grid-cols-[80px_1fr_150px_120px_130px_100px] gap-4 border-b border-zinc-900 px-4 py-3 text-[10px] uppercase tracking-widest text-zinc-600"><span>Job</span><span>Run / rule</span><span>Status</span><span>Attempts</span><span>Updated</span><span>Action</span></div>
 {filtered.length===0?<div className="px-4 py-12 text-center text-sm text-zinc-600">No pipeline jobs match this filter.</div>:filtered.map(j=><div key={j.id} className="grid grid-cols-[80px_1fr_150px_120px_130px_100px] gap-4 border-b border-zinc-900 px-4 py-4 text-xs"><div className="font-mono text-zinc-600">#{j.id}</div><div><Link href={`/runs/${encodeURIComponent(j.run_id)}`} className="font-mono text-zinc-300 hover:text-white">{j.run_id}</Link><div className="mt-1 truncate text-zinc-600">{j.rule_path}</div>{j.last_error&&<div className="mt-2 text-red-400/80">{j.last_error}</div>}</div><div>{badge(j.status)}</div><div className="font-mono text-zinc-500">{j.attempts} / {j.max_attempts}</div><div className="text-zinc-600">{new Date(j.updated_at).toLocaleString()}</div><div>{(j.status==="failed"||j.status==="cancelled")&&<button disabled={busy===j.id} onClick={()=>retry(j.id)} className="rounded border border-zinc-800 px-2 py-1 text-[10px] text-zinc-400 hover:border-zinc-600 hover:text-white disabled:opacity-40">{busy===j.id?"Queueing…":"Retry"}</button>}</div></div>)}</div>
 </main></div></div>
}