package store

import ("context"; "sort"; "sync"; "time")
type pipelineMemoryState struct { mu sync.Mutex; events map[string][]*RunEvent; jobs map[int64]*PipelineJob; nextID int64 }
var pipelineStates sync.Map
func memoryPipelineState(m *MemoryStore)*pipelineMemoryState{if v,ok:=pipelineStates.Load(m);ok{return v.(*pipelineMemoryState)};s:=&pipelineMemoryState{events:map[string][]*RunEvent{},jobs:map[int64]*PipelineJob{}};v,_:=pipelineStates.LoadOrStore(m,s);return v.(*pipelineMemoryState)}
func(m *MemoryStore)AppendRunEvent(_ context.Context,e *RunEvent)error{s:=memoryPipelineState(m);s.mu.Lock();defer s.mu.Unlock();e.ID=int64(len(s.events[e.RunID])+1);e.CreatedAt=time.Now();cp:=*e;s.events[e.RunID]=append(s.events[e.RunID],&cp);return nil}
func(m *MemoryStore)ListRunEvents(_ context.Context,runID string,limit int)([]*RunEvent,error){s:=memoryPipelineState(m);s.mu.Lock();defer s.mu.Unlock();out:=make([]*RunEvent,0,len(s.events[runID]));for _,e:=range s.events[runID]{cp:=*e;out=append(out,&cp)};sort.Slice(out,func(i,j int)bool{return out[i].CreatedAt.After(out[j].CreatedAt)});if limit>0&&len(out)>limit{out=out[:limit]};return out,nil}
func(m *MemoryStore)EnqueuePipelineJob(_ context.Context,j *PipelineJob)error{s:=memoryPipelineState(m);s.mu.Lock();defer s.mu.Unlock();for _,e:=range s.jobs{if e.RunID==j.RunID&&(e.Status=="queued"||e.Status=="running"){return nil}};s.nextID++;cp:=*j;cp.ID=s.nextID;if cp.Status==""{cp.Status="queued"};if cp.MaxAttempts<=0{cp.MaxAttempts=3};if cp.AvailableAt.IsZero(){cp.AvailableAt=time.Now()};cp.CreatedAt=time.Now();cp.UpdatedAt=cp.CreatedAt;s.jobs[cp.ID]=&cp;return nil}
func(m *MemoryStore)GetPipelineJob(_ context.Context,id int64)(*PipelineJob,error){s:=memoryPipelineState(m);s.mu.Lock();defer s.mu.Unlock();j,ok:=s.jobs[id];if !ok{return nil,ErrNotFound};cp:=*j;return &cp,nil}
func(m *MemoryStore)ListPipelineJobs(_ context.Context,limit int)([]*PipelineJob,error){s:=memoryPipelineState(m);s.mu.Lock();defer s.mu.Unlock();out:=make([]*PipelineJob,0,len(s.jobs));for _,j:=range s.jobs{cp:=*j;out=append(out,&cp)};sort.Slice(out,func(i,j int)bool{return out[i].CreatedAt.After(out[j].CreatedAt)});if limit>0&&len(out)>limit{out=out[:limit]};return out,nil}
func(m *MemoryStore)RetryPipelineJob(_ context.Context,id int64)error{s:=memoryPipelineState(m);s.mu.Lock();defer s.mu.Unlock();j,ok:=s.jobs[id];if !ok{return ErrNotFound};j.Status="queued";j.Attempts=0;j.LastError="";j.LockedBy="";j.LockedAt=nil;j.AvailableAt=time.Now();j.UpdatedAt=time.Now();return nil}
func(m *MemoryStore)ClaimPipelineJob(_ context.Context,workerID string,lease time.Duration)(*PipelineJob,error){s:=memoryPipelineState(m);s.mu.Lock();defer s.mu.Unlock();now:=time.Now();var sel *PipelineJob;for _,j:=range s.jobs{if j.Status=="running"&&j.LockedAt!=nil&&now.Sub(*j.LockedAt)>lease{j.Status="queued";j.LockedBy="";j.LockedAt=nil};if j.Status=="queued"&&!j.AvailableAt.After(now)&&(sel==nil||j.ID<sel.ID){sel=j}};if sel==nil{return nil,ErrNoJobAvailable};sel.Status="running";sel.Attempts++;sel.LockedBy=workerID;t:=now;sel.LockedAt=&t;sel.UpdatedAt=now;cp:=*sel;return &cp,nil}
func(m *MemoryStore)CompletePipelineJob(_ context.Context,id int64,status,lastError string)error{s:=memoryPipelineState(m);s.mu.Lock();defer s.mu.Unlock();j,ok:=s.jobs[id];if !ok{return ErrNotFound};j.Status=status;j.LastError=lastError;j.LockedBy="";j.LockedAt=nil;j.UpdatedAt=time.Now();return nil}
func(m *MemoryStore)RequeuePipelineJob(_ context.Context,id int64,delay time.Duration,lastError string)error{s:=memoryPipelineState(m);s.mu.Lock();defer s.mu.Unlock();j,ok:=s.jobs[id];if !ok{return ErrNotFound};j.Status="queued";j.LastError=lastError;j.LockedBy="";j.LockedAt=nil;j.AvailableAt=time.Now().Add(delay);j.UpdatedAt=time.Now();return nil}
func(m *MemoryStore)CancelPipelineJob(_ context.Context,runID string)error{s:=memoryPipelineState(m);s.mu.Lock();defer s.mu.Unlock();for _,j:=range s.jobs{if j.RunID==runID&&(j.Status=="queued"||j.Status=="running"){j.Status="cancelled";j.LastError="cancelled by operator";j.LockedBy="";j.LockedAt=nil;j.UpdatedAt=time.Now()}};return nil}
